### ISSUE TITLE
Synchronizing VLP16 without GPS

### ISSUE THREAD

**Issue by andre-nguyen** [googlecartographer/cartographer#1246]
Hi there,

wasn't sure where to ask this question as it relates to the hardware side of things. We all know accurate time stamping is important but how do you go about time synching when you don't have a GPS (indoor operation) to provide the VLP16 with? Did anyone end up using the linux pps API to timestamp the lidar?

Thanks!

**Comment by Entropy512** [comment]
I haven't personally needed that level of precision, although in my case I was recording data and processing it offline - so the machine was operating at very low CPU load.

You're mainly going to see an issue if the timestamps of multiple sensors are very inconsistent or have high jitter.  This GENERALLY becomes less of a problem if you set up the velodyne node to deliver one point cloud message per packet (default is one per revolution or half revolution depending on if you enabled dual returns mode), and have Cartographer accumulate the scans.

At least in my experience, two VLP-16 units and a Microstrain IMU, with the velodyne node configured for npackets=1, gave great results when recorded on a ThinkPad E470 that wasn't doing anything else.

However, if using a SICK LMS100 with the default driver and the num_subdivisions_per_laser_scan option caused issues, because if there is enough timing jitter that the delta between two scan timestamps is ever less than (real scan period)*(num_subdivisions_per_laser_scan-1)/(num_subdivisions_per_laser_scan), you will get an immediate fatal error.
