### ISSUE TITLE
Question: why tsdf? is it better for scan matching compared to probability grid?

### ISSUE THREAD

**Issue by kings-landing** [googlecartographer/cartographer#1533]

**Comment by pifon2a** [comment]
It is comparable in CPU time and matching quality. It is more expensive to insert data in TSDF grid than into a probability grid, but it gives you better convergence in optimization, because the cost function is a bit more regular. Also it is easier to build a mesh out of TSDF grid, which is a nice bonus.

**Comment by fzheng010** [comment]
Thanks! If I understand correctly, for 2D SLAM, TSDF is comparable to probability grid, but for 3D SLAM, it has an edge, in terms of convergence property and meshing. Is it right? @pifon2a

**Comment by pifon2a** [comment]
For 3D SLAM it should have an edge, but I cannot say for sure, since it is not yet implemented in Cartographer.
