### ISSUE TITLE
Is that possible to manually indicate loops?

### ISSUE THREAD

**Issue by nangong** [googlecartographer/cartographer#190]
Thanks to this great work , cartographer works very well in indoor environment. 
I am current using cartographer to map a large area, but I found the loop closure does not work in such environment.

![image](https://cloud.githubusercontent.com/assets/2638853/22318300/54f1d5e0-e3b4-11e6-8e85-a655a747e33c.png)

In the picture , the two branches are actually the same place. Are there any APIs for manually fixing error loop detection?

**Comment by SirVer** [comment]
> I am current using cartographer to map a large area, but I found the loop closure does not work in such environment.

We mapped city scales with Cartographer no problem. It is likely that your problem is elsewhere:
Maybe you need to tune your parameters better. If you provide us with bag, urdf, launch files and your config we might be able to help. Also it seems you are building a 2D map - is your laser always level? Is your floor really flat? Do you have an IMU?

> Are there any APIs for manually fixing error loop detection?

No. This is feasible to add in the optimization problem, but it was not really necessary.

**Comment by SirVer** [comment]
Closing. Please open a new bug with data + bags + config if you want tuning help.
