### ISSUE TITLE
How to fix that laser drift when launch cartographer?

### ISSUE THREAD

**Issue by b2220333** [googlecartographer/cartographer#301]
Here is the drift video:
https://www.dropbox.com/s/01jp5lh6jho5l1j/laser_error.mp4?dl=0

---Below is my settings---
include "map_builder.lua"
include "trajectory_builder.lua"

options = {
  map_builder = MAP_BUILDER,
  trajectory_builder = TRAJECTORY_BUILDER,  
  --sensor_bridge = {
    --horizontal_laser_min_range = 0.02,
    --horizontal_laser_max_range = 5.6,
    --horizontal_laser_missing_echo_ray_length = 1.2,
    --constant_odometry_translational_variance = 0.,
    --constant_odometry_rotational_variance = 0.,
  --},
  map_frame = "map",
  --tracking_frame = "laser",
  tracking_frame = "hokuyo_link",
  --published_frame = "laser",
  published_frame = "hokuyo_link",
  odom_frame = "odom",
  provide_odom_frame = true,
  use_odometry = false,
  --use_odometry_data = false,
  use_laser_scan = true,
  use_multi_echo_laser_scan = false,
  num_point_clouds = 0,
  
  --use_constant_odometry_variance = true,
  --constant_odometry_translational_variance = 1e-2,
  --constant_odometry_rotational_variance = 1e-1,
  --use_horizontal_laser = true,
  --use_horizontal_multi_echo_laser = false,
  
  --horizontal_laser_min_range = 0.1,  
  --horizontal_laser_max_range = 30.,  
  --horizontal_laser_missing_echo_ray_length = 5.,
  --num_lasers_3d = 0,
  lookup_transform_timeout_sec = 0.2,
  submap_publish_period_sec = 0.3,
  pose_publish_period_sec = 5e-3,
}
--此列必須為true，否則會發生Check failed: options.use_trajectory_builder_2d() != options.use_trajectory_builder_3d() (0 vs. 0) 
MAP_BUILDER.use_trajectory_builder_2d = true
TRAJECTORY_BUILDER_2D.use_imu_data = false
TRAJECTORY_BUILDER_2D.use_online_correlative_scan_matching = true
SPARSE_POSE_GRAPH.optimization_problem.huber_scale = 1e2
return options

<launch>
  <node name="cartographer_node" pkg="cartographer_ros"
      type="cartographer_node" args="
          -configuration_directory $(find willie_research_object_search_architecture)/config
          -configuration_basename beebot.lua"
      output="screen">
    <remap from="scan" to="scan" />
  </node>
</launch>

Here is how I run:
cd code/catkin_ws/
source install_isolated/setup.bash
cd
roslaunch willie_research_object_search_architecture beebot_google_cartographer.launch

Thank you~

**Comment by SirVer** [comment]
I do not see any drift in your video. I see that the laser points are jumping, but since the map is not changing (i.e. this data is not inserted into the map) I think this is a visualization artifact.

My guess is that you are replaying a rosbag that contains `tf` messages. And these already contain some transforms that Cartographer is publishing, i.e. `map -> base_link`. These are generated by Cartographer and should not be replayed from canned data. What you see is rViz sometimes deciding to use the old tf's that are replayed and sometimes the new ones currently created by Cartographer which are correct to transform the point cloud.

Our PR2 sample data has the same problem, so we provide a small script to remove these transforms. You should be fine by adding [this block](https://github.com/googlecartographer/cartographer_ros/blob/master/cartographer_ros/launch/demo_pr2.launch#L29) to your launch file.
