### ISSUE TITLE
Does cartographer work with RGB-D camera?How?

### ISSUE THREAD

**Issue by ghost069** [googlecartographer/cartographer#524]
I tried the demo and it came out successfully.
![2017-09-13 12 55 09](https://user-images.githubusercontent.com/30897881/30360328-4764fc3e-9883-11e7-8ed4-ce52c8668383.png)
However I want to apply cartographer with RGB-D camera ,but it's all about laser data.I thought it's not going to work with RGB-D camera but the documentation didn't specifically point out it.(Or maybe it's just me...)
So,anyway,if I want to construct a map like the one below,is it possible with cartographer?If it's possible,what are the extra work that i should do to construct a map like this?I mean,with color,shape and all the other stuff.
Thanks a lot for your kind help!
![mmexport1505280081538 1](https://user-images.githubusercontent.com/30897881/30361064-827e0bb8-9887-11e7-9118-1435062ab146.jpg)

**Comment by Entropy512** [comment]
It does support depth cameras - I'm not sure if it uses the color information at all.  If you follow the commit history, you'll see that quite a few of the inputs to Cartographer were renamed to be more generic since not all sensors that generate point clouds are lasers.

https://github.com/googlecartographer/cartographer_turtlebot

**Comment by cschuet** [comment]
It does support depth cameras in theory, but the results are quite bad. We believe this is due to RGB-D cameras having a different noise model than laser scanners. I have opened #545 to track this issue.
