### ISSUE TITLE
Sensor combination for outdoor SLAM

### ISSUE THREAD

**Issue by GITSHOHOKU** [googlecartographer/cartographer#556]
Hi Guys
   I want to use a combination of RGB-D and Velodyne 16 Lidar for outdoor SLAM project.I don't know if
an IMU is neccesorry to make sure this combination have enough real-time ability and accuracy in practice?
    Many thanks in advance!
Hongkunlong

**Comment by cschuet** [comment]
Hi Hongkunlong,

We currently don't have a good story for RGB-D data. The naive approach of converting that to a (uncolored - discarding RGB) point cloud and feeding it into cartographer seems to generate unsatisfactory results (I hear - I haven't tried myself). I filed #545 since RGB-D data is a popular request, but I can't promise when we will have time to address this.

Are you planning to run our 2D or 3D pipeline, i.e. do you want a 2D or 3D map at the end?

Cheers,
Christoph

**Comment by SirVer** [comment]
Closing as this issue is not actionable for us.
