### ISSUE TITLE
Invalid argument passed to canTransform argument source_frame in tf2 frame_ids cannot be empty

### ISSUE THREAD

**Issue by will1991** [googlecartographer/cartographer#765]

**Comment by cschuet** [comment]
Can you provide additional information? What happened? What were you trying to do?

**Comment by DennisBian** [comment]
The long corridor problem makes it really difficult to get the correct pose without using odometry ,  slam think the robot is not moving when laser scan datas are almost the same at long corridor, thus i think using odometry might sloves the problem.  However, I have met the same issue when i set
  tracking_frame = "base_link",
  published_frame = "base_link",
  odom_frame = "odom",
  provide_odom_frame = true,
  use_odometry = false,

**Comment by ojura** [comment]
The sensor messages you are passing to Cartographer probably have an empty frame id, which is invalid.

**Comment by MichaelGrupp** [comment]
@DennisBian `provide_odom_frame` does not mean that you use a separate odometry source, that's the job of `use_odometry`. See also [here](https://github.com/googlecartographer/cartographer_ros/blob/master/docs/source/configuration.rst). If you still have problems, I'd recommend to open a separate issue since this "long corridor" problem is not really related to the original post here.

**Comment by DennisBian** [comment]
@MichaelGrupp sorry for my mistake typing, i just setting the "use_odometry = true,"  and when i changed the odom topic name as remap from "odometry" ,i have fixed this problem.

**Comment by gaschler** [comment]
Closing this as answered. Feel free to re-open if needed.
