### ISSUE TITLE
Can you explain the architecture of the current code?

### ISSUE THREAD

**Issue by sunmk2006** [googlecartographer/cartographer#953]
hello,I notice that the current version(release 0.3.0 or master) is quite different from the previous version(release 0.2.0 or 0.1.0). for example,kalman_filter,bazel,cartographer_grpc ,metrics folders and so on,Why is there such major changes?What's the advantage of doing this ?Can you explain the architecture of the current code or provide some documentation?

**Comment by gaschler** [comment]
Since ~October 2017, all large changes are discussed and documented in the "request for comment" process: https://github.com/googlecartographer/rfcs
The RFC documents there (and maybe some open house slides) are the documentation we have.
Large changes that people currently work on are listed in https://github.com/googlecartographer/cartographer/projects
